extends: airbnb-base
parser: "babel-eslint"
plugins:
  - import
rules:
  "no-param-reassign": 0
  "guard-for-in": 0
  "comma-dangle": 0
  "padded-blocks": 0
  "prefer-const": 0
  "symbol-description": 0
  "no-multi-assign": 0
  "no-restricted-syntax": 0
